name: Deploy Preview to Railway

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  pull-requests: write
  contents: read

jobs:
  deploy-preview:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    environment: preview-deploy
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy preview
        id: railway-deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway link -p ${{ vars.RAILWAY_PROJECT_ID }}
          railway environment create pr-${{ github.event.pull_request.number }} || true

          # Deploy and capture the deployment domain
          # We use --json to get a machine-readable response
          railway up --environment pr-${{ github.event.pull_request.number }} --detach

          # echo "DEPLOY_URL=https://$DEPLOY_URL" >> $GITHUB_OUTPUT

      - name: Comment with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            # const url = "${{ steps.railway-deploy.outputs.DEPLOY_URL }}";
            const envName = "pr-${{ github.event.pull_request.number }}";

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `ðŸª¿ ðŸª¿ ðŸª¿ Preview environment **${envName}** ready!\nðŸª¿ ðŸª¿ ðŸª¿Take a gander: [TO BE DONE]`
            })

  cleanup-preview:
    if: github.event.action == 'closed'
    environment: preview-cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Delete Railway Environment
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway link -p ${{ vars.RAILWAY_PROJECT_ID }}
          railway environment delete pr-${{ github.event.pull_request.number }} --yes
